### PR TITLE
Allow nginx config to be (possibly mounted) files

### PR DESCRIPTION
**Pull request by Kagee**

### CODE REVIEW

**Comment by ostefano** [comment]
I believe -f is enough. Can you test whether the `regular file` for the `-f` test includes symbolic links? My local tests say yes.

**Comment by Kagee** [comment]
Yes, i'll rewrite it to -f:
````
$ [[ -f ./somefolder ]] && echo "True" || echo "False"
False
$ [[ -f ./symlinktofolder ]] && echo "True" || echo "False"
False
$ [[ -f ./softlinktomissingfile ]] && echo "True" || echo "False"
False

$ [[ -f ./theoriginalfile ]] && echo "True" || echo "False"
True
$ [[ -f ./hardlinktoriginalfile ]] && echo "True" || echo "False"
True
$ [[ -f ./softlinktoriginalfile ]] && echo "True" || echo "False"
True
````

**Comment by Kagee** [comment]
Changed, up for review

**Comment by Kagee** [comment]
Merged

**Pull request closed without merging**
