### PR TITLE
Rename HOSTNAME to BASEURL

### PR DESCRIPTION
**Pull request by Kagee**
backward compatible with HOSTNAME -> BASEURL

### CODE REVIEW

**Comment by ostefano** [comment]
Tell me more about HOST_ORG_ID and where/why EXT_BASEURL would  be used?

**Comment by Kagee** [comment]
To be honest, i would probably suggest *all* "hard coded" settings are setup like i.e. HOST_ORG_ID, ``"${HOST_ORG_ID-1}"``, with a sensible default (1), but possible to override with a optional env var. This is just the two settings i looked at first.

**Comment by Kagee** [comment]
There is not so much to say about EXT_BASEURL, apart from that it allows the user to set MISP.external_baseurl to something different than BASEURL/HOSTNAME, the way it was. external_baseurl is when you for <reasons> want the MISP to answer on two domains.

**Comment by Kagee** [comment]
Looking at this, i must have been confused as to what MISP.external_baseurl was used for. I'll just revert this to HOSTNAME -> BASEURL only.

**Comment by Kagee** [comment]
Going to need rewrite in a lot of time.

**Pull request closed without merging**
